federation_version: =2.7.0
subgraphs:
  users:
    routing_url: http://localhost:4001/api
    schema:
      file: ../apps/users/schema.graphql
  products:
    routing_url: http://localhost:4002/api
    schema:
      file: ../apps/products/schema.graphql
  reviews:
    routing_url: http://localhost:4003/api
    schema:
      file: ../apps/reviews/schema.graphql
